# This is a Visual Studio extension installation task for Dev Box.

name: install-vs-extension
description: Installs a Visual Studio extension
author: Microsoft Corporation
command: ".\\Install-VSIXExtension.ps1 -MarketplaceItemName {{marketplaceItemName}}"
inputs:
  marketplaceItemName:
    type: string
    required: true
documentation:
  notes: This task is used to install a Visual Studio extension.
  examples:
    - task: install-vs-extension
      description: Install GitHub Copilot
      inputs:
        marketplaceItemName: GitHub.copilotvs
