# This is a git repository cloning task for Dev Box

name: git-clone
description: Clones a git repository.
author: Microsoft Corporation
command: ./main.ps1 -RepositoryUrl {{repositoryUrl}} -Directory {{directory}} -Branch {{branch}} -Pat {{pat}}
inputs:
  repositoryUrl:
    defaultValue: ''
    type: string
    required: true
    description:
  directory:
    defaultValue: C:\Workspaces
    type: string
    required: false
    description: 
    defaultValue: ''
    type: string
    required: false
    description: 
  pat:
    defaultValue: ''
    type: string
    required: false
    description: 
  examples:
    - task: git-clone
      description: Clone this repository into C:\Workspaces
      inputs:
        repositoryUrl: https://github.com/microsoft/calculator
        directory: C:\Workspaces
    - task: git-clone
      description: Clone this repository's feature/winui2.6 branch into C:\Workspaces
      inputs:
        repositoryUrl: https://github.com/microsoft/calculator
        directory: C:\Workspaces
        branch: feature/winui2.6
