# This is a simple powershell command execution task for Dev Box.

name: powershell
description: Execute a powershell command.
author: Microsoft Corporation
command: ".\\Run-Command.ps1 -Command {{command}} -WorkingDirectory {{workingDirectory}}"
inputs:
  command:
    type: string
    defaultValue: ""
    required: true
    description: The command to execute.
  workingDirectory:
    type: string
    defaultValue: ""
    required: false
    description: The working directory to execute the command in.
documentation:
  notes: This task is used to execute a powershell command.
  examples:
    - task: powershell
      description: print hello world
      inputs:
        command: "Write-Host 'hello, world!'"
    - task: powershell
      description: run script
      inputs:
        command: "./script.ps1"
        workingDirectory: C:\\provisioning\\temp
